{"uuid": "217a1325-8a5c-4229-bdd4-115c45fbeb3f", "children": ["4348d142-7b31-4cd6-86e3-c67dc77e27a9"], "befores": [{"name": "browser", "status": "passed", "start": 1617605890118, "stop": 1617605891479}], "afters": [{"name": "browser::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\n  (Session info: chrome=89.0.4389.114)\n\n", "trace": "  File \"D:\\Sonu\\personal\\xeneta-test\\python-page-object\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"D:\\Sonu\\personal\\xeneta-test\\python-page-object\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\Sonu\\personal\\xeneta-test\\python-page-object\\tests\\plugins\\browser.py\", line 9, in browser\n    browser.driver().close()\n  File \"D:\\Sonu\\personal\\xeneta-test\\python-page-object\\demoauto\\driver\\web_driver.py\", line 28, in close\n    self._driver.close()\n  File \"D:\\Sonu\\personal\\xeneta-test\\python-page-object\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 688, in close\n    self.execute(Command.CLOSE)\n  File \"D:\\Sonu\\personal\\xeneta-test\\python-page-object\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Sonu\\personal\\xeneta-test\\python-page-object\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1617605892476, "stop": 1617605896586}], "start": 1617605890118, "stop": 1617605896586}